---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: rabbit-pod-autoscaler
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rabbit-pod-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbit-pod-autoscaler
subjects:
  - kind: ServiceAccount
    name: rabbit-pod-autoscaler
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-pod-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-pod-autoscaler
  template:
    metadata:
      labels:
        app: rabbit-pod-autoscaler
    spec:
      serviceAccountName: rabbit-pod-autoscaler
      containers:
        - name: rabbit-pod-autoscaler
          image: onfido/k8s-rabbit-pod-autoscaler
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          env:
            - name: INTERVAL
              value: "30"
            - name: RABBIT_HOST
              value: "http://rabbitmq.example.com"
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit-pod-autoscaler
                  key: rabbit-user
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbit-pod-autoscaler
                  key: rabbit-pass
            - name: AUTOSCALING
              value: >
                3|10|5|development|example|example.queue|vhost;
                3|5|3|development|example2|example2.queue|vhost
            - name: LOGS
              value: HIGH
            - name: SLACK_HOOK
              value: SLACK_HOOK
